# Offense count: 1
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/landrush/cap/linux/read_host_visible_ip_address_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/landrush/action/teardown.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'lib/landrush/config.rb'
    - 'test/support/fake_ui.rb'

# Offense count: 7
Metrics/AbcSize:
  Max: 38

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 52
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 157

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 29

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 14

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Exclude:
    - 'Gemfile'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'lib/landrush/action/redirect_dns.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Exclude:
    - 'lib/landrush/cap/linux/add_iptables_rule.rb'
    - 'lib/landrush/cap/linux/read_host_visible_ip_address.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
Style/BlockDelimiters:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'lib/landrush/cap/debian/install_iptables.rb'
    - 'lib/landrush/cap/redhat/install_iptables.rb'
    - 'lib/landrush/plugin.rb'
    - 'test/landrush/cap/linux/read_host_visible_ip_address_test.rb'
    - 'test/landrush/store_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Exclude:
    - 'lib/landrush/server.rb'

# Offense count: 8
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/support/clear_dependent_vms.rb'
    - 'test/support/fake_resolver_config.rb'
    - 'test/support/fake_working_dir.rb'
    - 'test/support/test_server_daemon.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Exclude:
    - 'lib/landrush/server.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Exclude:
    - 'lib/landrush/store.rb'

# Offense count: 23
# Configuration parameters: Exclude.
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/DoubleNegation:
  Exclude:
    - 'lib/landrush/config.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'test/landrush/resolver_config_test.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'test/landrush/resolver_config_test.rb'
    - 'test/landrush/server_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/landrush/command.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Exclude:
    - 'test/landrush/cap/linux/read_host_visible_ip_address_test.rb'

# Offense count: 6
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/landrush/action/install_prerequisites.rb'
    - 'lib/landrush/action/setup.rb'
    - 'lib/landrush/action/teardown.rb'
    - 'test/support/fake_resolver_config.rb'
    - 'test/support/test_server_daemon.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
Style/HashSyntax:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'lib/landrush/config.rb'
    - 'test/support/fake_resolver_config.rb'
    - 'test/support/test_server_daemon.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/Lambda:
  Exclude:
    - 'lib/landrush/plugin.rb'
    - 'test/landrush/action/setup_test.rb'
    - 'test/landrush/action/teardown_test.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/NegatedIf:
  Exclude:
    - 'lib/landrush/action/setup.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Exclude:
    - 'lib/landrush/action/setup.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Not:
  Exclude:
    - 'lib/landrush/action/setup.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 2
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Exclude:
    - 'test/support/test_server_daemon.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'landrush.gemspec'
    - 'lib/landrush/cap/linux/redirect_dns.rb'
    - 'test/landrush/action/setup_test.rb'
    - 'test/landrush/store_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Exclude:
    - 'lib/landrush/cap/linux/read_host_visible_ip_address.rb'

# Offense count: 13
# Cop supports --auto-correct.
Style/Proc:
  Exclude:
    - 'test/landrush/action/setup_test.rb'
    - 'test/landrush/action/teardown_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'lib/landrush/dependent_vms.rb'
    - 'lib/landrush/server.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'lib/landrush/server.rb'
    - 'lib/landrush/store.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'lib/landrush/resolver_config.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'lib/landrush/cap/linux/read_host_visible_ip_address.rb'
    - 'lib/landrush/command.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'lib/landrush/command.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceAfterMethodName:
  Exclude:
    - 'lib/landrush/server.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Style/SpaceAroundOperators:
  Exclude:
    - 'lib/landrush/store.rb'
    - 'test/landrush/server_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Exclude:
    - 'landrush.gemspec'
    - 'test/test_helper.rb'

# Offense count: 61
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Exclude:
    - 'lib/landrush/cap/linux/read_host_visible_ip_address.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Exclude:
    - 'lib/landrush/cap/linux/add_iptables_rule.rb'
    - 'lib/landrush/cap/linux/redirect_dns.rb'
    - 'test/landrush/action/teardown_test.rb'
    - 'test/support/fake_working_dir.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Exclude:
    - 'lib/landrush/action/common.rb'
    - 'test/landrush/cap/linux/configured_dns_servers_test.rb'
    - 'test/landrush/cap/linux/redirect_dns_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Exclude:
    - 'examples/Vagrantfile'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, IgnoreClassMethods, Whitelist.
Style/TrivialAccessors:
  Exclude:
    - 'lib/landrush/config.rb'
    - 'lib/landrush/server.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'landrush.gemspec'
    - 'lib/landrush/cap/linux/add_iptables_rule.rb'
    - 'lib/landrush/cap/linux/read_host_visible_ip_address.rb'
