Vagrant.configure('2') do |config|
  config.vm.box = '{{box}}'
  config.vm.hostname = 'my-host.my-tld'
  config.vm.network :private_network, ip: '10.10.10.123'

  config.landrush.enabled = true
  config.landrush.tld = 'my-tld'
end
