# 
# This serves as a simple example, and it's what I'm using for testing locally.
#
# If you're doing development and want to run this locally you can simply
# `bundle install`, then prefix all your vagrant commands with `bundle exec`, like so:
#
#   VAGRANT_CWD=examples bundle exec vagrant up
#   VAGRANT_CWD=examples bundle exce vagrant halt
#

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

  config.landrush.enable

  config.vm.hostname = "myhost.vagrant.dev"

  config.landrush.host 'static1.example.com', '1.2.3.4'
  config.landrush.host 'static2.example.com', '2.3.4.5'
end
